### ISSUE TITLE
can't load assets (imgs) when use server

### ISSUE THREAD

**Issue by ghost** [K4rian/twserver-go#1]
can't load assets (imgs) when use server

img can load when I open index.html directly

**Comment by K4rian** [comment]
Hi,

Did you try to load your images from the (default) _www_ directory by any chance?
The HTTP Server only serves the wiki index and, thus, ignore other files such as images, css and so on.

If you need to display an image in your wiki, you could:
- Import (drag and drop) your image from any local folder to the wiki page opened in your web browser _(on the top of the page)_.
- Use an external URL.

I'll update the code to serve any directory in a future commit, which should fix your issue.

Thanks for the highlight.

**Comment by K4rian** [comment]
@stuscu Take a look at the updated [README](https://github.com/K4rian/twserver-go/blob/v0.3/README.md#customizing) and check out the [latest release](https://github.com/K4rian/twserver-go/releases/tag/v0.3).
