### ISSUE TITLE
[BUG] Delete a tiddler does not trigger a save

### ISSUE THREAD

**Issue by kookma** [K4rian/twserver-go#3]
When you create a new tiddler, twserver-go triggers a save
BUT when you delete a tiddler twserver-go does not trigger a save and you have to manually click on save!

It seems some of actions need to manually click on the save button

**Comment by K4rian** [comment]
Hi, thanks for your interest in the project.

I've just tested adding and deleting a tiddler, and the save is triggered automatically as intended.
Do you still have this issue?

**Comment by kookma** [comment]
For me using the latest version save triggers only on adding and modifying tiddlers.
- Win 10 / Edge 112 / TW 5.2.7
I noticed this is the same is with Timimi saver! 
On Node.JS, a save triggers when you delete a tiddler!

**Comment by K4rian** [comment]
Unfortunately, I wasn't able to reproduce the bug mentioned.

I've captured some footage on a fresh installed VM (Win10 Enterprise 22H2 x64, Edge 112.0.X) and everything worked as intended. You can download the video [here](https://anonfiles.com/I92fH0n5z7/twserver_go_2023_04_26_mp4) (~8 MB).

Same results on Chrome/Chromium and Firefox (both Standard and Developer Edition).

**Comment by kookma** [comment]
Thank you!
